version: "2"
services:
  video-reproduction-ms:
      build:
        context: ./
      ports: 
      - 3002:3002
      tty: true
      depends_on:
      - mongodb

  mongodb:
        image: mongo:latest
        container_name: "mongodb"
        environment:
          - MONGO_DATA_DIR=/data/db
          - MONGO_LOG_DIR=/dev/null
        volumes:
          - ./data/db:/data/db
        entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs0" ]
        ports:
            - 27017:27017
